# version: '3.4'

name: hms-gitgang

services:
  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=hms_gitgang.settings
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - hms_db
  #     - redis
      
  hms_db:
    restart: always
    image: postgres:16.3-alpine3.20
    container_name: hms_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "127.0.0.1"]

  # web:
  #   build: .
  #   command: daphne -b 0.0.0.0 -p 8000 hms_gitgang.asgi:application --reload
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - hms_db
  #     - redis

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"

  

volumes:
  postgres_data: