# version: '3.4'

name: hms-gitgang

# services:
  # hms_db
  
services:
  hms_db:
    restart: always
    image: postgres:16.3-alpine3.20
    container_name: hms_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"

  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000 --reload
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - hms_db

volumes:
  postgres_data: