
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: gitgang_postgres
      POSTGRES_USER: callmekay
      POSTGRES_PASSWORD: Callmekay@4891
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver --reload 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: